load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "LibC",
    srcs = glob([
        "*.swift",
    ]),
    module_name = "LibC",
    deps = [],
    visibility = ["//visibility:public"],
)